[[pages]]
name = ""
icon = "ðŸ˜·"
is_section = true

[[pages]]
path = "pages/introPage.py"
name = "Subject,"
icon = ""

[[pages]]
name = "ðŸ™‚"
icon = ""
is_section = true

[[pages]]
path = "pages/componentOfPersonalityPage.py"
name = "Component of Personality"
icon = ""

[[pages]]
path = "pages/goalsOfTheProjectPage.py"
name = "Goals of the Project"
icon = ""

[[pages]]
path = "pages/methodologyPage.py"
name = "Methodology"
icon = ""



